[package]
name = "produ_engine"
version = "0.1.0"
authors = ["Galileo <Galileo-dev@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.30.0"
winit = "0.24.0"
