[package]
name = "shade_runner"
version = "0.1.0"
authors = ["Tom Gowan <tomrgowan@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4"
shaderc = "0.3"
spirv-reflect = "0.2"
vulkano = "0.11"

[dev-dependencies]
vulkano = "0.11"
color-backtrace = "0.1" 
difference = "2"

[patch.crates-io]
vulkano = { git = "https://github.com/mitchmindtree/vulkano", branch = "nannou_patches" }
