[package]
name = "shade_runner"
version = "0.1.0"
authors = ["Tom Gowan <tomrgowan@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4"
shaderc = "0.5"
spirv-reflect = "0.2"
vulkano = "0.12"

[dev-dependencies]
color-backtrace = "0.1" 
difference = "2"
